### ISSUE TITLE
Add a new "key" or "password" icon for password input fields

### ISSUE THREAD

**Issue by mhstoller** [proksh/atomize#10]
Currently there is a user icon that can potentially be used for a username input field, but there is not a corresponding password icon. It would be cool to have a key icon that can be used to represent password fields.

The username input field from the docs is used as an example with the UserSolid logo:
```
// Input With Right Button
import { Input, Icon } from "atomize";

const InputWithRightButton = () => {
  return (
    <Input
      placeholder="User Name"
      p={{ x: "2.5rem" }}
      prefix={
        <Icon
          name="UserSolid"
          color="warning800"
          size="16px"
          cursor="pointer"
          pos="absolute"
          top="50%"
          left="0.75rem"
          transform="translateY(-50%)"
        />
      }
    />
  );
}
```

**Comment by ghost** [comment]
Added 'Lock' & 'LockSolid' icons. Hope that helps :)

**Comment by mhstoller** [comment]
Thank you!
