### ISSUE TITLE
Add "Power" icon

### ISSUE THREAD

**Issue by mhstoller** [proksh/atomize#13]
Could a "Power" icon be added to the project? Something like: https://fontawesome.com/icons/power-off?style=solid

:)

**Comment by mhstoller** [comment]
Also, could "Pause" and "Stop" icons be added as well, to complement the "Play" icon?

**Comment by mhstoller** [comment]
Sorry! I'm also in need of a "refresh"/"redo" icon like: https://fontawesome.com/icons/redo-alt?style=solid

Am I better off just importing Font Awesome? I don't mean to add a lot of work for you, but it might make the project more complete with more icons

**Comment by proksh** [comment]
I have added the Icons you have asked for. I am actually working on using Font awesome for atomize react too, it will be difficult to make all the icons by me. :)

Till then you can import Font Awesome if you need more icons.
