### ISSUE TITLE
target="_blanc" should be target="_blank"

### ISSUE THREAD

**Issue by fabiancook** [proksh/atomize#15]
`target="_blanc"` should be `target="_blank"`

`target="_blanc"` does work, but if you go back to the webpage and click another link using `target="_blanc"` it will replace the previously clicked on link, as `_blanc` is the window name being opened rather than the "special" `_blank` name 

Reference https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attr-target

**Comment by fabiancook** [comment]
Looks like this more applies to https://github.com/proksh/atomize-docs

**Comment by proksh** [comment]
Hey thanks, fixed it :)
