### ISSUE TITLE
computeDivStyle - TypeError: Cannot read property 'rounded' of null

### ISSUE THREAD

**Issue by mhstoller** [proksh/atomize#16]
Getting an error with the Div.style.js file when running my project. Not sure if this is an atomize problem, or maybe a styletron-react issue... I've attached a screenshot of the error output
![image](https://user-images.githubusercontent.com/36415486/63523718-a4450200-c4c8-11e9-9bf0-651c55d3b5b2.png)

**Comment by mhstoller** [comment]
Reverting to atomize@1.0.9 fixes the issue, but I couldn't test the newer version (looks like 1.0.15 was made in recent commits) because the latest one available from yarn is 1.0.10

**Comment by proksh** [comment]
Fixed this issue, I just forgot to define a default theme. Thank you.
