### ISSUE TITLE
Styletron error on atomize@1.0.16

### ISSUE THREAD

**Issue by mhstoller** [proksh/atomize#17]
My page doesn't render a stylesheet correctly, the icons render as full page, and the styles from atomize are gone.

The error in console is:
```
Styletron has been switched to a no-op (test) mode.

A Styletron styled component was rendered, but no Styletron engine instance was provided in React context.

Did you forget to provide a Styletron engine instance to React context via using the Styletron provider component?

Note: Providers and Consumers must come from the exact same React.createContext call to work.
If your app has multiple instances of the "styletron-react" package in your node_module tree,
your Provider may be coming from a different React.createContext call, which means the styled components
will not recieve the provided engine instance. This scenario can arise, for example, when using "npm link".
```

**Comment by ghost** [comment]
Can you give me some sample code for what is causing the issue? Or link to the repository if it is public so that I could check that.

**Comment by mhstoller** [comment]
Here's a simple test code snippet for App.js:

```
import React from 'react';

// import { StyleReset } from 'atomize';
import { Div, Button, Input, Checkbox, Label, Image, Text, Icon } from "atomize";


function App() {

  return( <Input
    placeholder="enter text"
    type="text"
    p={{ x: "2.25rem" }}
    w="600px"
    prefix={
      <Icon
        name="LockSolid"
        color="info700"
        size="16px"
        cursor="pointer"
        pos="absolute"
        top="50%"
        left="0.75rem"
        transform="translateY(-50%)"
      />
    }
    suffix={
      <Button
        pos="absolute"
        bg="transparent"
        w="3rem"
        top="0"
        right="0"
        rounded={{ r: "md" }}
        type="button"
      >
        <Icon
          name="Eye"
          color="danger800"
          size="16px"
        />
      </Button>
    }
    value="test"
  />)
}

export default App;
```

On Atomize 1.0.9, it displays as expected:
![image](https://user-images.githubusercontent.com/36415486/63865778-1f526080-c980-11e9-9e6b-1877494df5ee.png)



With Atomize 1.0.16 it displays like this:
![image](https://user-images.githubusercontent.com/36415486/63865800-29745f00-c980-11e9-8635-4a0bc8665ecb.png)



Error in console:
```
Styletron has been switched to a no-op (test) mode.

A Styletron styled component was rendered, but no Styletron engine instance was provided in React context.

Did you forget to provide a Styletron engine instance to React context via using the Styletron provider component?

Note: Providers and Consumers must come from the exact same React.createContext call to work.
If your app has multiple instances of the "styletron-react" package in your node_module tree,
your Provider may be coming from a different React.createContext call, which means the styled components
will not recieve the provided engine instance. This scenario can arise, for example, when using "npm link".
```

**Comment by ghost** [comment]
Are you sure you have installed the style styletron correctly following - https://atomizecode.com/docs/react/setup ?

**Comment by mhstoller** [comment]
It seems that I didn't follow that, as after wrapping the application with the StyletronProvider and passing an instance of Styletron to it, things are working properly on atomize 1.0.16.

Sorry about that, and thanks for the help!

**Comment by subodhk01** [comment]
@mhstoller Can you elaborate your solution, I'm facing the same issue

**Comment by LucaMoro96** [comment]
![image](https://user-images.githubusercontent.com/22317834/102618324-d907ae80-413a-11eb-8f9b-d81ad2209680.png)

Hi @subodhk01!
This is my index.js setup of Styletron and it works fine, try to follow the steps at https://www.styletron.org/getting-started#with-react.

**Comment by subodhk01** [comment]
Ohh yeah got it, actually I was using nextjs so I had to configure it a bit differently. Nevertheless Thanks!!

**Comment by LucaMoro96** [comment]
I had a similiar situation when I used it for a Gatsby website, I understand you!
