### ISSUE TITLE
hoverColor for "Power" icon not working

### ISSUE THREAD

**Issue by mhstoller** [proksh/atomize#18]
I can't get the hoverColor property for the "Power" icon to work, but it works with other icons. You can use the following code for a quick test:

```
<Icon name="Power" size="1.5rem" hoverColor="info700" />
<Icon name="Refresh" size="1.5rem" hoverColor="info700" />
```

Hovering over the refresh icon will properly apply the hover color, but for the power icon it does not work (at least for me it doesn't).

Setting a CSS class on the icon element, and applying a fill property when hovered does work correctly, so I can use that as a workaround for now.

HTML:
`<Icon className="icon-test" name="Power" size="1.5rem" />
`

CSS:
```
.icon-test:hover {
  fill: red;
}
```

**Comment by ghost** [comment]
Thanks @mhstoller ,

Fixed this issue in version 1.0.19. Sorry for the delayed response.
