### ISSUE TITLE
Theme does not work with Gatsby JS

### ISSUE THREAD

**Issue by ColinTS** [proksh/atomize#24]
My theme file used to work with Gatsby JS however it no longer does. Error is "Type Error: Cannot read property 'colors' of undefined"

This is how I have it in the gatsby-browser.js file to wrap my app in the ThemeProdiver component:

```
import React from "react"
import { ThemeProvider, StyleReset } from "atomize"

import theme from "constants/theme"

export const wrapRootElement = ({ element }) => (
  <ThemeProvider theme={theme}>
    <StyleReset />
    {element}
  </ThemeProvider>
)

```

**Comment by ghost** [comment]
I think it is not a problem with the theme but some component of atomize. Can you comment out "element" and check if it still gives an error or not?
