### ISSUE TITLE
The Row, Col system doesn't work as expected in my Create-React-App project.

### ISSUE THREAD

**Issue by areoformed** [proksh/atomize#37]
Hola!

I've been trying out your design system and we can't seem to make the layout system work. We've tried different permutations, used examples from your documentation, installed styletron, uninstalled, but it hasn't worked. There seems to be a larger issue here but we can't tell what it is.

Could you please have a look? https://gitlab.com/armlaurent/atomize-bug

Cheers

**Comment by LucaMoro96** [comment]
Hi!

I think that the problem could be that there is no <StyletronProvider> tag in index.js!
This is my index.js render method:

`ReactDOM.render(
    <StyletronProvider value={engine} debug={debug} debugAfterHydration>
        <ThemeProvider theme={theme}>
            <StyleReset />
            <App />
        </ThemeProvider>
    </StyletronProvider>,
    document.getElementById('root')
);`

Hope this could be useful!

**Comment by sowmenappd** [comment]
@LucaMoro96 yes, that's correct. 

@arlaurent The index.js file doesn't have the `StyletronProvider` wrapper around the App component. Also, it doesn't have the `ThemeProvider`, that is a problem here. 

Please consider closing this issue.

**Comment by areoformed** [comment]
Thank you so much for replying. :)

I'm closing the issue! The reply really did help.
