### ISSUE TITLE
Password Input Mask

### ISSUE THREAD

**Issue by Hey-Feres** [proksh/atomize#40]
### How could I set secure password input to my Atomize Inputs?

- I need something like the html result of:

`<input type="password" />`

**Comment by BennyBzH** [comment]
You can do an import of `Input`, then give it a `type=password`

Example : 
```javascript
import { Input } from "atomize";

class InputPassword extends React.Component {
    render() {
    return (
      <Input
        placeholder="Password"
        type="password" />
    );
  }
}
```

Did this answer help you ?

**Comment by Hey-Feres** [comment]
Thanks, it solve my problem.

**Comment by Hey-Feres** [comment]
I was using a function written by me to replace the chars with "*" to troubleshoot it. But this "type" props make everything more clean and easy.
