### ISSUE TITLE
Input and textarea available prop for existing copy  

### ISSUE THREAD

**Issue by drewbrophy** [proksh/atomize#49]
I was trying to place text (not placeholder text) in the input and textarea by default. I did not see any prop to do this but mirroring standard HTML I tried using: 

`      <Input
        placeholder="Headline"
        value="What Fields Do You Care About?"
      />`

This allowed for the value to appear, but not it appears to be frozen (the value can not be changed). Is there a way to place an initial value but then for the user to be able to change it? 

Thank you in advance! Atomize has been game changing so I'm grateful for all of your work on it.

**Comment by LucaMoro96** [comment]
Maybe try setting the state that controls the input and use that value in the value field of `<Input />`

`const [text, setText] = useState("default text value")`

**Comment by drewbrophy** [comment]
Thank you so much.
