### ISSUE TITLE
Can't resolve './dist' in 'node_modules/atomize'

### ISSUE THREAD

**Issue by evilboss** [proksh/atomize#58]
Looks like dist folder is missing from your repo when installed
![image](https://user-images.githubusercontent.com/11191727/121704378-4c94e200-cb06-11eb-977c-41110c1a1cc6.png)

**Comment by faggionluca** [comment]
Can confirm the dist folder is missing in the 1.0.27 version

**Comment by trojancode** [comment]
dist folder is missing in new update

**Comment by proksh** [comment]
Fixed the issue. Thanks for raising the issue. :)

**Comment by trojancode** [comment]
use version 1.0.26
