### ISSUE TITLE
Atomize with Angular?

### ISSUE THREAD

**Issue by Ademking** [proksh/atomize#7]
It would be cool to use this beautiful desgin with Angular. I hope

**Comment by proksh** [comment]
Yes, but I am trying to fixing the React system first. Would think of it after that. 😃

**Comment by Ademking** [comment]
it's ok for us to start migrating this project to angular ?

**Comment by proksh** [comment]
Yes, it's open-source. Just don't take the name 'atomize' before asking us. 😆
