### ISSUE TITLE
Custom Font

### ISSUE THREAD

**Issue by balazsbarta** [proksh/atomize#8]
Can I add custom font to the `fontFamily`? I know I can add Google Fonts, but how can I add custom webfonts if it's possible? I can't find anything in the docs related to this. Thanks!

**Comment by proksh** [comment]
You can add '<link .... />' to add your fonts.

If not, you can use a CSS file and import it in your root directory - https://www.yudiz.com/adding-new-fonts-in-react-js/

After this, you can define that font family in theme - https://atomizecode.com/docs/react/theme
