### ISSUE TITLE
Add meta informations on the repository

### ISSUE THREAD

**Issue by frinyvonnick** [proksh/atomize#9]
Hi, thank you for your work 👍 

Actually the top of your repository is empty. It suggest to fill the missing meta data:

- website
- short description
- Related topics (tags)

![image](https://user-images.githubusercontent.com/13099512/62372375-a0f8cf00-b537-11e9-8228-72dd3cdc9f5e.png)

**Comment by proksh** [comment]
Hey, Thanks 😃. Did it.
